project:
  type: website
  output-dir: docs

website:
  favicon: favicon.png
  title: "Fundamentos de Machine Learning"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Lectures"
        contents:
          - lectures/clase_0.qmd
      - section: "Practicas"
        contents:
          - tps/tp_0.qmd
          - tps/tp_1.qmd
          - tps/tp_2.qmd
          - tps/tp_3.qmd
          - tps/tp_4.qmd
format:
  html:
    theme: cosmo
    toc: true